baseURL: "https://yatheen07.github.io/ypkm-blogs/"
title: <YPKM />
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5
                - name: Resume
                  url: resume/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "YPKM Blogs"
    author: Yatheendra Pravan

    defaultTheme: dark
    #disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
      Title: "Hola!👋"
      Content: >
          Presently, I am a Student at [Trinity College Dublin](https://www.tcd.ie/), pursuing Master's in Computer Science, specializing in Intelligent Systems.
          - I write about Mathematics, Machine learning and Chess.
    
    socialIcons:
          - name: github
            url: "https://github.com/Yatheen07/"
          - name: linkedin
            url: "https://www.linkedin.com/in/yatheendra-pravan/"
          - name: RsS
            url: "index.xml"